site_name: Zicx 的笔记本
site_author: Zicx
site_url: "https://zicx.top/notebook"
site_description: Zicx's Notebook.

repo_name: cxzhou35/notebook
repo_url: https://github.com/cxzhou35/notebook/
edit_uri: tree/main/docs/

copyright: Copyright &copy; 2022-2023 <a href="https://github.com/cxzhou35" target="_blank" rel="noopener">Zicx</a>

nav:
  - "主页":
      - index.md
      - "讨论区": diss.md
      - "近期更新": update.md
  - "课程笔记":
      - course/index.md
      - "计算机科学":
          - course/cs/index.md
          - "CS106L":
              - course/cs/cs106L/index.md
              - "课程介绍": course/cs/cs106L/lec01_intro.md
              - "类型和结构": course/cs/cs106L/lec02_types_and_structs.md
              # - "流和流对象": course/cs/cs106L/lec03_streams.md
              # - "初始化和引用": course/cs/cs106L/lec04_init_and_ref.md
              # - "容器": course/cs/cs106L/lec05_containers.md
              # - "迭代器和指针": course/cs/cs106L/lec06_iterators_and_pointers.md
              # - "类和对象": course/cs/cs106L/lec07_classes.md
              # - "模板": course/cs/cs106L/lec08_templates.md
              # - "方程和 Lambda 表达式": course/cs/cs106L/lec09_funcs_and_lambdas.md
              # - "操作符重载": course/cs/cs106L/lec10_operator_overloading.md
              # - "特殊成员函数": course/cs/cs106L/lec11_special_member_functions.md
              # - "类型安全": course/cs/cs106L/lec12_type_safety.md
              # - "其他话题": course/cs/cs106L/lec13_special_topics.md
          - "CS231n":
              - course/cs/cs231n/index.md
              - "课程介绍": course/cs/cs231n/lec01_introduction_overview.md
              - "图像分类任务": course/cs/cs231n/lec02_image_classification.md
          - "Deep Learning Systems":
              - course/cs/dlsys/index.md
          - "数据结构与算法":
              - course/cs/ds/index.md
          - "计算机视觉导论":
              - course/cs/icv/index.md
          - "数值分析":
              - course/cs/na/index.md
          - "面向对象编程":
              - course/cs/oop/index.md
          - "操作系统":
              - course/cs/os/index.md
      - "光电":
          - course/opt/index.md
          - "光电子学":
              - course/opt/optoelec/index.md
      - "数学":
          - course/math/index.md
  - "备忘录":
      - memo/index.md
      - "常用工具":
          - memo/tool/index.md
          - "Git":
              - memo/tool/git/index.md
          - "Shell":
              - memo/tool/shell/index.md
          - "CMake":
              - memo/tool/cmake/index.md
          - "Docker":
              - memo/tool/docker/index.md
          - "LaTeX":
              - memo/tool/latex/index.md
          - "NumPy":
              - memo/tool/numpy/index.md
          - "Neoim":
              - memo/tool/nvim/index.md
          - "MATLAB":
              - memo/tool/matlab/index.md
          - "Conda":
              - memo/tool/conda/index.md
          - "Pytorch":
              - memo/tool/pytorch/index.md
          - "Markdown":
              - memo/tool/markdown/index.md
          - "Tmux":
              - memo/tool/tmux/index.md
          - "FFmpeg":
              - memo/tool/ffmpeg/index.md
      - "编程语言":
          - memo/pl/index.md
          - "C++":
              - memo/pl/cpp/index.md
          - "Python":
              - memo/pl/python/index.md
          - "Go":
              - memo/pl/go/index.md
          - "Rust":
              - memo/pl/rust/index.md
          - "Julia":
              - memo/pl/julia/index.md
          - "Lua":
              - memo/pl/lua/index.md
      - "环境搭建":
          - memo/config/index.md
          - "Windows":
              - memo/config/win/index.md
              - "Scoop":
                  - memo/config/win/scoop/index.md
          - "Mac":
              - memo/config/mac/index.md
              - "Homebrew":
                  - memo/config/mac/homebrew/index.md
          - "Linux":
              - memo/config/linux/index.md
  - "科研":
      - research/index.md
      - "NeRF":
          - research/nerf/index.md
          - "论文笔记": research/nerf/note.md
          - "数学推导": research/nerf/math.md
          - "代码学习": research/nerf/code.md
  - "生活":
      - life/index.md
      - "影视":
          - life/film/index.md
      - "阅读":
          - life/reading/index.md
  - "杂项":
      - others/index.md

theme:
  name: material
  language: zh
  font: false
  favicon: paw.svg
  icon:
    edit: material/file-edit-outline
    view: material/file-eye-outline
    logo: octicons/cloud-24
    repo: fontawesome/brands/git-alt
    # admonition:
    #   info: fontawesome/solid/anchor
    #   note: fontawesome/solid/pen-nib
    #   abstract: fontawesome/solid/list
    #   tip: fontawesome/solid/lightbulb
    #   success: fontawesome/solid/check
    #   question: fontawesome/solid/circle-question
    #   warning: fontawesome/solid/triangle-exclamation
    #   failure: material/alien
    #   danger: fontawesome/solid/virus
    #   bug: fontawesome/solid/robot
    #   example: fontawesome/solid/flask
    #   quote: fontawesome/solid/quote-left
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  custom_dir: overrides

plugins:
  - glightbox
  - tags
  - search
  - statistics:
      page_check_metadata: comments
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
      exclude:
        - index.md
        - update.md
        - diss.md
        - course/index.md
        - memo/index.md
        - life/index.md

markdown_extensions:
  - toc:
      permalink: true # link for each title
  - admonition
  - abbr
  - attr_list
  - def_list
  - tables
  - footnotes
  - meta
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      user: cxzhou35
      repo: notebook
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: none
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: diagram
          class: diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  analytics:
    provider: google
    property: G-4P08GMSPJM
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cxzhou35
      name: Github
    - icon: fontawesome/brands/telegram
      link: https://telegram.me/cxzhou35
      name: Telegram
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cxzhou35
      name: Twitter
    - icon: fontawesome/solid/rss
      link: https://zicx.top/
      name: Blog
    - icon: fontawesome/solid/house
      link: https://zicx.top/home/
      name: Home

extra_css:
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
  - https://cdn.tonycrane.cc/utils/katex.min.css
  - _css/flink.css
  - _css/tony.css

extra_javascript:
  # mermaid support
  # - https://unpkg.com/mermaid@9.1.7/dist/mermaid.min.js

  # katex support
  - _js/katex.js
  - https://cdn.tonycrane.cc/utils/katex.min.js

  # table sort support
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - _js/tablesort.js
