site_name: Zicx の Notebook
site_author: Zicx
site_url: 'https://zicx.top/notebook'

repo_name: xuer04/notebook
repo_url: https://github.com/xuer04/notebook
edit_uri: blob/main/docs

theme: 
  name: material
  language: zh
  icon:
    logo: bootstrap/paw
    repo: fontawesome/brands/github-alt
    admonition:
      info: fontawesome/solid/anchor
      note: fontawesome/solid/pen-nib
      abstract: fontawesome/solid/list
      tip: fontawesome/solid/lightbulb
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: material/alien
      danger: fontawesome/solid/virus
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  font:
    text: Share Tech
    code: JetBrains Mono
  palette:
    scheme: default
    accent: teal
    primary: deep purple
  features:
    - content.code.annotate
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
  custom_dir: overrides

plugins:
  - glightbox
  - search
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
      exclude:
        - index.md
        - comming.md
        - link.md
        - tech_accu/index.md

markdown_extensions:
  - toc:
      permalink: true # link for each title
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - mdx_math

copyright: 'Copyright &copy 2022 Zicx'

extra:
  analytics:
    provider: google
    property: G-4P08GMSPJM
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Xuer04
      name: Github

extra_css:
  - _css/flink.css

extra_javascript: 
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - _js/extra.js




nav:
  - "主页": 
    - "主页": index.md
    - "讨论区": link.md
  - "备忘录":
    - tech_accu/index.md
    - "常用工具":
      - tech_accu/tool/index.md
      - "Git Something":
        - tech_accu/tool/Git/index.md
        - tech_accu/tool/Git/Workflow/index.md
        - tech_accu/tool/Git/Commands/index.md
      - tech_accu/tool/Shell/index.md
      - tech_accu/tool/Colab/index.md
    - "标准 | 格式 | 规范":
      - tech_accu/standard/BVH_format/index.md
