site_name: Zicx's Notebook
site_author: Zicx
site_url: "https://zicx.top/notebook"
site_description: Zicx's Notebook.

repo_name: xuer04/notebook
repo_url: https://github.com/xuer04/notebook
edit_uri: tree/main/docs

copyright: Copyright &copy; 2022-2023 <a href="https://github.com/Xuer04" target="_blank" rel="noopener">Zicx</a>

nav:
  - "Home":
      - index.md
      - "Discussion": diss.md
      - "Update": update.md
  - "Course":
      - course/index.md
      - "CS":
          - course/cs/index.md
          - "CS106L":
              - course/cs/cs106L/index.md
          - "CS231n":
              - course/cs/cs231n/index.md
          - "Deep Learning Systems":
              - course/cs/dlsys/index.md
          - "Data Structure":
              - course/cs/ds/index.md
          - "计算机视觉导论":
              - course/cs/icv/index.md
          - "数值分析":
              - course/cs/na/index.md
          - "面向对象编程":
              - course/cs/oop/index.md
          - "操作系统":
              - course/cs/os/index.md
      - "OPT":
          - course/opt/index.md
          - "光电子学":
              - course/opt/optoelec/index.md
      - "Math":
          - course/math/index.md
  - "Memo":
      - memo/index.md
      - "Tool":
          - memo/tool/index.md
          - "Git":
              - memo/tool/git/index.md
          - "Shell":
              - memo/tool/shell/index.md
          - "Cmake":
              - memo/tool/cmake/index.md
          - "Docker":
              - memo/tool/docker/index.md
          - "LaTeX":
              - memo/tool/latex/index.md
          - "Lua":
              - memo/tool/lua/index.md
          - "Julia":
              - memo/tool/julia/index.md
          - "Numpy":
              - memo/tool/numpy/index.md
          - "Vim":
              - memo/tool/vim/index.md
          - "Matlab":
              - memo/tool/matlab/index.md
          - "Conda":
              - memo/tool/conda/index.md
          - "Markdown":
              - memo/tool/markdown/index.md
      - "Configuration":
          - memo/config/index.md
          - "Windows":
              - memo/config/win/index.md
              - "Scoop":
                  - memo/config/win/scoop/index.md
          - "Mac":
              - memo/config/mac/index.md
              - "Homebrew":
                  - memo/config/mac/homebrew/index.md
          - "Linux":
              - memo/config/linux/index.md
  - "Life":
      - life/index.md
  - "Others":
      - others/index.md

theme:
  name: material
  language: zh
  font: false
  favicon: paw.svg
  icon:
    logo: octicons/cloud-24
    repo: fontawesome/brands/github-alt
    edit: material/pencil
    admonition:
      info: fontawesome/solid/anchor
      note: fontawesome/solid/pen-nib
      abstract: fontawesome/solid/list
      tip: fontawesome/solid/lightbulb
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: material/alien
      danger: fontawesome/solid/virus
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - toc.follow
  custom_dir: overrides

plugins:
  - glightbox
  - search
  - statistics:
      page_check_metadata: comments
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
      exclude:
        - index.md
        - update.md
        - diss.md
        - course/index.md
        - memo/index.md
        - life/index.md
        - course/cs/index.md
        - course/math/index.md
        - course/opt/index.md
        - memo/tool/index.md
        - memo/config/index.md

markdown_extensions:
  - toc:
      permalink: true # link for each title
      toc_depth: 4
  - admonition
  - abbr
  - attr_list
  - def_list
  - tables
  - footnotes
  - meta
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: none
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      # options:
      #   custom_icons:
      #     - overrides/.icons
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  analytics:
    provider: google
    property: G-4P08GMSPJM
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Xuer04
      name: Github
    - icon: fontawesome/brands/telegram
      link: https://telegram.me/Xuer04
      name: Telegram
    - icon: fontawesome/solid/rss
      link: https://zicx.top/
      name: Blog
    - icon: fontawesome/solid/house
      link: https://zicx.top/home/
      name: Home

extra_css:
  # - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css
  - https://cdn.tonycrane.cc/utils/katex.min.css
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
  - _css/flink.css
  - _css/custom.css
  - _css/giscus.css
  - _css/fold_toc.css
  - _css/counter.css
  - _css/card.css

extra_javascript:
  - https://cdn.tonycrane.cc/utils/katex.min.js
  - _js/katex.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - _js/tablesort.js
  # - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

