site_name: Zicx の Notebook
site_author: Zicx
site_url: "https://zicx.top/notebook"

repo_name: xuer04/notebook
repo_url: https://github.com/xuer04/notebook
edit_uri: blob/main/docs

theme:
  name: material
  language: zh
  favicon: paw.svg
  icon:
    logo: octicons/cloud-24
    repo: fontawesome/brands/github-alt
    admonition:
      info: fontawesome/solid/anchor
      note: fontawesome/solid/pen-nib
      abstract: fontawesome/solid/list
      tip: fontawesome/solid/lightbulb
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: material/alien
      danger: fontawesome/solid/virus
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  font:
    text: Roboto
    code: JetBrains Mono
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
  custom_dir: overrides

plugins:
  - glightbox
  - search
  - statistics
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
      exclude:
        - index.md
        - update.md
        - diss.md

markdown_extensions:
  - toc:
      permalink: true # link for each title
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - mdx_math

copyright: "Copyright &copy 2022 Zicx"

extra:
  analytics:
    provider: google
    property: G-4P08GMSPJM
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Xuer04
      name: Github
    - icon: fontawesome/brands/telegram
      link: https://telegram.me/Xuer04
      name: Telegram

extra_css:
  - _css/flink.css
  - _css/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  # - _js/extra.js
  - _js/mathjax.js
  - _js/tablesort.js

nav:
  - "Home":
      - index.md
      - "Discussion": diss.md
      - "Update": update.md
  - "Course":
      - course/index.md
      - "CS":
          - course/cs/index.md
          - "CS106L":
              - course/cs/cs106L/index.md
          - "CS231n":
              - course/cs/cs231n/index.md
          - "Deep Learning System":
              - course/cs/dlsys/index.md
          - "Data Structure":
              - course/cs/ds/index.md
          - "Introduction to Computer Vision":
              - course/cs/icv/index.md
          - "Numerical Analysis":
              - course/cs/na/index.md
          - "Object-Oriented Programming":
              - course/cs/oop/index.md
          - "Operating System":
              - course/cs/os/index.md
      - "OPT":
          - course/opt/index.md
      - "Math":
          - course/math/index.md
  - "Memo":
      - memo/index.md
      - "Tool":
          - memo/tool/index.md
          - "Git":
              - memo/tool/git/index.md
          - "Shell":
              - memo/tool/shell/index.md
          - "Cmake":
              - memo/tool/cmake/index.md
          - "Docker":
              - memo/tool/docker/index.md
          - "LaTeX":
              - memo/tool/latex/index.md
